#!/bin/bash

CURRENT_DIR="$(cd "$(dirname "$0")" >/dev/null && pwd)"

component=$1


comp_home=$CURRENT_DIR/$component

if [ -e "$comp_home/start.sh" ]; then
    echo "starting $component ..."
    cd $comp_home && $comp_home/start.sh
else
    echo "no component $component"
fi
