name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v0.1.0, v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11" # Or your project's primary Python version

    - name: Install uv and build tool
      run: |
        pip install uv
        uv pip install build # Install the 'build' package

    - name: Build package
      run: |
        python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # No 'with' block for PyPI token needed here if using trusted publishing.
      # The action will automatically use the OIDC token.
      # Ensure PyPI is configured for trusted publishing from this repository.

    # Optional: Create a GitHub Release
    - name: Create GitHub Release
      uses: actions/create-release@v1
      if: success() # Only run if publish was successful
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Release notes for ${{ github.ref_name }}
          *(Auto-generated by GitHub Actions)*
        draft: false
        prerelease: false
